### PR TITLE
Make Dashboard page

### LINKED ISSUE #6: Website Dashboard Analyst

### PR DESCRIPTION
**Pull request by oliviasully**

### CODE REVIEW

**Comment by CassieColby** [comment]
Can you send me a preview link?

**Comment by oliviasully** [comment]
> Can you send me a preview link?

https://deploy-preview-17--symphonious-trifle-c055e8.netlify.app/

**Comment by CassieColby** [comment]
Looks like the old version? Don't see the collection or dashboard tabs. Am I missing them?

**Comment by oliviasully** [comment]
> Looks like the old version? Don't see the collection or dashboard tabs. Am I missing them?

It should be the correct version. I just checked the link and it looks right.

**Review by MangoSwirl — APPROVED** [review]
LGTM!

**Comment by CassieColby** [comment]
Looks good!

**Review by CassieColby — APPROVED** [review]
Good work!

**Pull request merged**
